/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab1;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
       
        List list = new List();
        MemoryIO memIO = new MemoryIO();
        MemoryController memoryController = new MemoryController();

        list = memoryController.firstFit(memIO, list);
        
        List list2 = new List();
        MemoryIO memIO2 = new MemoryIO();
        MemoryController memoryController2 = new MemoryController();

        list2 = memoryController2.bestFit(memIO2, list2);
        try {
            memIO2.writeToFile(list, list2, 0, memoryController2);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
