/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab1;

public class App {

    public static void main(String[] args) {
       
        MemoryManager mem = new MemoryManager();
        MemoryIO memIO = new MemoryIO();
        
        MemoryController memoryController = new MemoryController();
        memoryController.firstFit(mem, memIO);
        
        MemoryManager mem2 = new MemoryManager();
        MemoryIO memIO2 = new MemoryIO();
        
        MemoryController memoryController2 = new MemoryController();
        memoryController2.bestFit(mem2, memIO2);
    }
}
